# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode12

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
